# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true

    trusted_hosts: ['^(.+\.)?roks\.gg', '^localhost$', '^172.105.87.155$']
    trusted_proxies: '127.0.0.1,REMOTE_ADDR'
    trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port']

    session:
        enabled: true
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    php_errors:
        log: true

