security:
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    encoders:
        App\Entity\User:
            algorithm: auto
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\DiscordAuthenticator
            logout:
                path: app_logout
                target: index
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path: /

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_LUGAL_MEMBER: [ROLE_USER]
        ROLE_OFFICER: [ROLE_LUGAL_MEMBER]
        ROLE_ADMIN: [ROLE_OFFICER, ROLE_SCRIBE, ROLE_EDIT_ROLES]
        ROLE_SUPERADMIN: [ROLE_ADMIN]
