twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        site_title: '%site_title%'
        site_analytics_id: '%site_analytics_id%'