version: "3.7"

services:
  app:
    build: .
    env_file:
      - .env.local
    volumes:
      - phpsocket:/var/run/php
      - .:/var/www
      - ./google_sheets_credentials.json:/var/www/google_sheets_credentials.json
    links:
      - db

  web:
    image: nginx:1.19.6-alpine
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - phpsocket:/var/run/php
      - .:/var/www
      - ./var/uploads:/var/www/public/uploads
    depends_on:
      - app
    links:
      - app

  db:
    image: postgres:13.1-alpine
    restart: always
    env_file:
      - .env.db.local
    volumes:
      - ./var/db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - db

volumes:
  phpsocket: