parameters:
    site_title: '%env(SITE_TITLE)%'
    env(SITE_TITLE): Kingdom X
    site_analytics_id: '%env(SITE_ANALYTICS_ID)%'
    env(SITE_ANALYTICS_ID): horse
    api_token: '%env(API_TOKEN)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $uploadsDir: '%kernel.project_dir%/public/uploads/'
            $uploadsPublicDir: 'uploads/'
            $siteTitle: '%env(SITE_TITLE)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
